let table = prompt("Enter Any Table Number");
document.write("Table Of " + table);
document.write("<br>");
document.write("<br>");
document.write(table + " X " + 1 + " = " + table * 1);
document.write("<br>");
document.write(table + " X " + 2 + " = " + table * 2);
document.write("<br>");
document.write(table + " X " + 3 + " = " + table * 3);
document.write("<br>");
document.write(table + " X " + 4 + " = " + table * 4);
document.write("<br>");
document.write(table + " X " + 5 + " = " + table * 5);
document.write("<br>");
document.write(table + " X " + 6 + " = " + table * 6);
document.write("<br>");
document.write(table + " X " + 7 + " = " + table * 7);
document.write("<br>");
document.write(table + " X " + 8 + " = " + table * 8);
document.write("<br>");
document.write(table + " X " + 9 + " = " + table * 9);
document.write("<br>");
document.write(table + " X " + 10 + " = " + table * 10);
